/* 
 * Bitcoin API
 *
 * Blockchain Facilities
 *
 * OpenAPI spec version: 2.0.0
 * Contact: contato@astarlabs.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AStar.Api;
using AStar.Model;
using AStar.Client;
using System.Reflection;

namespace AStar.Test
{
    /// <summary>
    ///  Class for testing SingleResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SingleResultTests
    {
        // TODO uncomment below to declare an instance variable for SingleResult
        //private SingleResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SingleResult
            //instance = new SingleResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SingleResult
        /// </summary>
        [Test]
        public void SingleResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SingleResult
            //Assert.IsInstanceOfType<SingleResult> (instance, "variable 'instance' is a SingleResult");
        }

        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Test]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }
        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Test]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

    }

}
