/* 
 * Bitcoin API
 *
 * Blockchain Facilities
 *
 * OpenAPI spec version: 2.0.0
 * Contact: contato@astarlabs.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AStar.Api;
using AStar.Model;
using AStar.Client;
using System.Reflection;

namespace AStar.Test
{
    /// <summary>
    ///  Class for testing Transaction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TransactionTests
    {
        // TODO uncomment below to declare an instance variable for Transaction
        //private Transaction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Transaction
            //instance = new Transaction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Transaction
        /// </summary>
        [Test]
        public void TransactionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Transaction
            //Assert.IsInstanceOfType<Transaction> (instance, "variable 'instance' is a Transaction");
        }

        /// <summary>
        /// Test the property 'Creationdate'
        /// </summary>
        [Test]
        public void CreationdateTest()
        {
            // TODO unit test for the property 'Creationdate'
        }
        /// <summary>
        /// Test the property 'Confirmationdate'
        /// </summary>
        [Test]
        public void ConfirmationdateTest()
        {
            // TODO unit test for the property 'Confirmationdate'
        }
        /// <summary>
        /// Test the property 'Blockchaincreationdate'
        /// </summary>
        [Test]
        public void BlockchaincreationdateTest()
        {
            // TODO unit test for the property 'Blockchaincreationdate'
        }
        /// <summary>
        /// Test the property 'Txid'
        /// </summary>
        [Test]
        public void TxidTest()
        {
            // TODO unit test for the property 'Txid'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Fee'
        /// </summary>
        [Test]
        public void FeeTest()
        {
            // TODO unit test for the property 'Fee'
        }
        /// <summary>
        /// Test the property 'Txsize'
        /// </summary>
        [Test]
        public void TxsizeTest()
        {
            // TODO unit test for the property 'Txsize'
        }
        /// <summary>
        /// Test the property 'Txhex'
        /// </summary>
        [Test]
        public void TxhexTest()
        {
            // TODO unit test for the property 'Txhex'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Feepriority'
        /// </summary>
        [Test]
        public void FeepriorityTest()
        {
            // TODO unit test for the property 'Feepriority'
        }
        /// <summary>
        /// Test the property 'Confirmations'
        /// </summary>
        [Test]
        public void ConfirmationsTest()
        {
            // TODO unit test for the property 'Confirmations'
        }
        /// <summary>
        /// Test the property 'Errormessage'
        /// </summary>
        [Test]
        public void ErrormessageTest()
        {
            // TODO unit test for the property 'Errormessage'
        }
        /// <summary>
        /// Test the property 'Coin'
        /// </summary>
        [Test]
        public void CoinTest()
        {
            // TODO unit test for the property 'Coin'
        }
        /// <summary>
        /// Test the property 'Test'
        /// </summary>
        [Test]
        public void TestTest()
        {
            // TODO unit test for the property 'Test'
        }

    }

}
